from pathlib import Path
import sys

CODE_ROOT = Path(__file__).resolve().parents[1]
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from .engine import MinimalTRPGEngine, RuntimeOptions, create_initial_state, parse_player_action
from .models import (
    AgentRuntimeState,
    ConversationTurnRecord,
    CoreState,
    DeltaOperation,
    DicerOutput,
    DirectorOutput,
    DirectorState,
    GameMeta,
    GameState,
    LocationState,
    NPCContactChannel,
    NPCCurrentTask,
    NPCBackgroundBeat,
    NPCManagerOutput,
    NPCTimelineNote,
    NPCVisibleBeat,
    NpcState,
    ParsedPlayerAction,
    PlayerState,
    RuleSeed,
    RuntimeLogEvent,
    RuleState,
    ScenarioSeed,
    ScenarioState,
    SecretSeed,
    SceneState,
    ObjectiveSeed,
    TurnDebugTrace,
    TurnResult,
    TurnStreamEvent,
    TriggerSeed,
    build_rule_state,
)
from .prompt_loader import PromptRepository, ScenarioBundle

__all__ = [
    "DeltaOperation",
    "DicerOutput",
    "DirectorOutput",
    "DirectorState",
    "AgentRuntimeState",
    "ConversationTurnRecord",
    "CoreState",
    "GameMeta",
    "GameState",
    "LocationState",
    "MinimalTRPGEngine",
    "NPCBackgroundBeat",
    "NPCContactChannel",
    "NPCCurrentTask",
    "NPCManagerOutput",
    "NPCTimelineNote",
    "NPCVisibleBeat",
    "NpcState",
    "ParsedPlayerAction",
    "PlayerState",
    "PromptRepository",
    "ObjectiveSeed",
    "RuleSeed",
    "RuleState",
    "RuntimeOptions",
    "RuntimeLogEvent",
    "ScenarioSeed",
    "ScenarioState",
    "ScenarioBundle",
    "SceneState",
    "SecretSeed",
    "TurnResult",
    "TurnStreamEvent",
    "TurnDebugTrace",
    "TriggerSeed",
    "build_rule_state",
    "create_initial_state",
    "parse_player_action",
]
